export const products = [
  {
    id:1,
    img:"https://w0.peakpx.com/wallpaper/196/34/HD-wallpaper-virat-kohli-in-blue-jersey-virat-kohli-blue-indian-cricket-king-kohli-sports.jpg",
    link:"https://www.cricbuzz.com/profiles/1413/virat-kohli"
  },
  {
    id:2,
    img:"https://e0.pxfuel.com/wallpapers/667/27/desktop-wallpaper-virat-kohli-full-screen-virat-kohli-mobile-thumbnail.jpg",
    link:"https://instagram.com/virat.kohli?igshid=YmMyMTA2M2Y="
  },
  {
    id:3,
    img:"https://e1.pxfuel.com/desktop-wallpaper/521/44/desktop-wallpaper-virat-kohli-club%E2%84%A2-virat-kohli-full-screen-thumbnail.jpg",
    link:"https://instagram.com/virat.kohli?igshid=YmMyMTA2M2Y="
  },
  {
    id:4,
    img:"https://e1.pxfuel.com/desktop-wallpaper/909/393/desktop-wallpaper-pin-on-virat-kohli-virat-kohli-full-screen-thumbnail.jpg",
    link:"https://instagram.com/virat.kohli?igshid=YmMyMTA2M2Y="
  },
  {
    id:5,
    img:"https://newspaperads.ads2publish.com/wp-content/uploads/2019/06/american-tourister-look-our-for-the-bags-autographed-by-virat-kohli-ad-delhi-times-23-05-2019.png",
    link:"https://instagram.com/virat.kohli?igshid=YmMyMTA2M2Y="
  },
  {
    id:6,
    img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9YbJ0vNdqLTEIL88aUUGvZACIRllD5KhpnQ&usqp=CAU",
    link:"https://instagram.com/virat.kohli?igshid=YmMyMTA2M2Y="
  }
  
];